version: '3'

services:
    
  nginx:
    restart: always
    build:
      context: ./nginx
      dockerfile: Dockerfile.dev
    ports:
      - '4000:80'

  client:
    restart: always
    volumes:
      - /usr/app/node_modules
      - ./client:/usr/app
    build:
      context: ./client
      dockerfile: Dockerfile.dev
